<?php

namespace Database\Seeders;

use App\Models\Essence;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class EssenceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $essences = [
            ['nom_local' => 'Abalé', 'code' => '1401'],
            ['nom_local' => 'Abam à poils rouges', 'code' => '1402'],
            ['nom_local' => 'Abam aloa', 'code' => '1403'],
            ['nom_local' => 'Abam aloa à poils', 'code' => '1404'],
            ['nom_local' => 'Abam deloa', 'code' => '1923'],
            ['nom_local' => 'Abam ékuk', 'code' => '1405'],
            ['nom_local' => 'Abam ékuk békoé', 'code' => '1406'],
            ['nom_local' => 'Abam essiembot', 'code' => '1407'],
            ['nom_local' => 'Abam évélé', 'code' => '1408'],
            ['nom_local' => 'Abam fruit jaune', 'code' => '1409'],
            ['nom_local' => 'Abam GF', 'code' => '1410'],
            ['nom_local' => 'Abam kobi', 'code' => '1411'],
            ['nom_local' => 'Abam kwopé', 'code' => '1412'],
            ['nom_local' => 'Abam littoral', 'code' => '1413'],
            ['nom_local' => 'Abam mézimé', 'code' => '1414'],
            ['nom_local' => 'Abam ndinga mayo/nyabizane', 'code' => '1415'],
            ['nom_local' => 'Abam nsola', 'code' => '1416'],
            ['nom_local' => 'Abam sanaga goyoum', 'code' => '1417'],
            ['nom_local' => 'Abam tibati', 'code' => '1418'],
            ['nom_local' => 'Abam vrai', 'code' => '1419'],
            ['nom_local' => 'Abam yabem Nyong', 'code' => '1420'],
            ['nom_local' => 'Abaya', 'code' => '1421'],
            ['nom_local' => 'Abeek', 'code' => '3013'],
            ['nom_local' => 'Abem nlong', 'code' => '1422'],
            ['nom_local' => 'Abem osoé', 'code' => '1423'],
            ['nom_local' => 'Abena', 'code' => '1424'],
            ['nom_local' => 'Abena osoé / Bambi', 'code' => '1425'],
            ['nom_local' => 'Abeu', 'code' => '1426'],
            ['nom_local' => 'Abeu afan', 'code' => '1427'],
            ['nom_local' => 'Abeu bongo', 'code' => '1944'],
            ['nom_local' => 'Abeu GF', 'code' => '1429'],
            ['nom_local' => 'Abeu goro', 'code' => '1428'],
            ['nom_local' => 'Abeu osoé', 'code' => '1430'],
            ['nom_local' => 'Abing ntomba', 'code' => '1431'],
            ['nom_local' => 'Abip élé', 'code' => '1432'],
            ['nom_local' => 'Aboé', 'code' => '1435'],
            ['nom_local' => 'Abok ntanan', 'code' => '1436'],
            ['nom_local' => 'Abura', 'code' => '1437'],
            ['nom_local' => 'Abus', 'code' => '3207'],
            ['nom_local' => 'Acajou à GFo', 'code' => '1101'],
            ['nom_local' => 'Acajou blanc', 'code' => '1102'],
            ['nom_local' => 'Acajou de bassam', 'code' => '1103'],
            ['nom_local' => 'Acajou de Cayenne', 'code' => '1950'],
            ['nom_local' => 'Acanthus', 'code' => '3012'],
            ['nom_local' => 'Accormia', 'code' => '3015'],
            ['nom_local' => 'Acordia', 'code' => '3166'],
            ['nom_local' => 'Adenia', 'code' => '3139'],
            ['nom_local' => 'Adjap letouzey', 'code' => '1438'],
            ['nom_local' => 'Adjap londjap', 'code' => '1439'],
            ['nom_local' => 'Adjap mang', 'code' => '1440'],
            ['nom_local' => 'Adjap Nyong', 'code' => '1441'],
            ['nom_local' => 'Adjap osoé', 'code' => '1442'],
            ['nom_local' => 'Adjouaba', 'code' => '1443'],
            ['nom_local' => 'Afane', 'code' => '1444'],
            ['nom_local' => 'Afendeng', 'code' => '1445'],
            ['nom_local' => 'Afobilobi', 'code' => '1446'],
            ['nom_local' => 'Afromonum', 'code' => '1994'],
            ['nom_local' => 'Ageratum', 'code' => '3017'],
            ['nom_local' => 'Ahom ndamba', 'code' => '1447'],
            ['nom_local' => 'Aiélé / Abel', 'code' => '1301'],
            ['nom_local' => 'Akadak', 'code' => '1448'],
            ['nom_local' => 'Akak', 'code' => '1449'],
            ['nom_local' => 'Akak sang', 'code' => '1450'],
            ['nom_local' => 'Akee', 'code' => '1451'],
            ['nom_local' => 'Akee', 'code' => '3038'],
            ['nom_local' => 'Akela à fleurs rouges', 'code' => '1452'],
            ['nom_local' => 'Akendeng', 'code' => '1453'],
            ['nom_local' => 'Akeng', 'code' => '1454'],
            ['nom_local' => 'Akeng nkol', 'code' => '1455'],
            ['nom_local' => 'Akikubu', 'code' => '1456'],
            ['nom_local' => 'Ako A', 'code' => '1302'],
            ['nom_local' => 'Ako élé', 'code' => '1457'],
            ['nom_local' => 'Ako W', 'code' => '1303'],
            ['nom_local' => 'Akodiakédé', 'code' => '1458'],
            ['nom_local' => 'Akol / akoul', 'code' => '1459'],
            ['nom_local' => 'Akoua', 'code' => '1460'],
            ['nom_local' => 'Akoung elé', 'code' => '2011'],
            ['nom_local' => 'Akourna / Ossoko', 'code' => '1461'],
            ['nom_local' => 'Akpa', 'code' => '1462'],
            ['nom_local' => 'Akui', 'code' => '1463'],
            ['nom_local' => 'Alen / Palmier à huile', 'code' => '1472'],
            ['nom_local' => 'Alen ako', 'code' => '1464'],
            ['nom_local' => 'Alen essa', 'code' => '1465'],
            ['nom_local' => 'Alen kié', 'code' => '1466'],
            ['nom_local' => 'Alen motim', 'code' => '1467'],
            ['nom_local' => 'Alen okpwé / Dragonier', 'code' => '1469'],
            ['nom_local' => 'Alen okpwé letta', 'code' => '1468'],
            ['nom_local' => 'Alen zam', 'code' => '1470'],
            ['nom_local' => 'Alen zam bamiléké', 'code' => '1471'],
            ['nom_local' => 'Alep', 'code' => '1304'],
            ['nom_local' => 'Alomba / Essoula', 'code' => '1473'],
            ['nom_local' => 'Aloum', 'code' => '3018'],
            ['nom_local' => 'Alumbi', 'code' => '1474'],
            ['nom_local' => 'Amblica', 'code' => '1979'],
            ['nom_local' => 'Amvim', 'code' => '1475'],
            ['nom_local' => 'Amvout', 'code' => '1476'],
            ['nom_local' => 'Amvout à poils', 'code' => '1477'],
            ['nom_local' => 'Andim', 'code' => '1478'],
            ['nom_local' => 'Andinding', 'code' => '1479'],
            ['nom_local' => 'Andok', 'code' => '1480'],
            ['nom_local' => 'Andok Mouloundou', 'code' => '1481'],
            ['nom_local' => 'Andok ngoé', 'code' => '1482'],
            ['nom_local' => 'Andok osoé', 'code' => '1483'],
            ['nom_local' => 'Andoung brun', 'code' => '1305'],
            ['nom_local' => 'Andoung rose', 'code' => '1306'],
            ['nom_local' => 'Angakomo', 'code' => '1484'],
            ['nom_local' => 'Angelin', 'code' => '1485'],
            ['nom_local' => 'Angoan', 'code' => '1486'],
            ['nom_local' => 'Angoan osoé', 'code' => '1487'],
            ['nom_local' => 'Angossa', 'code' => '1488'],
            ['nom_local' => 'Angoyémé osoé', 'code' => '1489'],
            ['nom_local' => 'Angueuk', 'code' => '1307'],
            ['nom_local' => 'Aningré A', 'code' => '1201'],
            ['nom_local' => 'Aningré R', 'code' => '1202'],
            ['nom_local' => 'Annona Dimako', 'code' => '1490'],
            ['nom_local' => 'Annona Kribi', 'code' => '1491'],
            ['nom_local' => 'Annona Otitié', 'code' => '1492'],
            ['nom_local' => 'Anzem', 'code' => '1493'],
            ['nom_local' => 'Araucaria', 'code' => '1952'],
            ['nom_local' => 'Arbre à pain', 'code' => '1953'],
            ['nom_local' => 'Arongana', 'code' => '3085'],
            ['nom_local' => 'Artocarpus', 'code' => '3135'],
            ['nom_local' => 'Asian plum', 'code' => '1494'],
            ['nom_local' => 'Asila koufani / Kioro', 'code' => '1495'],
            ['nom_local' => 'Asila opfoil', 'code' => '1496'],
            ['nom_local' => 'Asila tambéré', 'code' => '1497'],
            ['nom_local' => 'Assa mingoung / Igaganga', 'code' => '1498'],
            ['nom_local' => 'Assa nkol Buea', 'code' => '3024'],
            ['nom_local' => 'Assam à poils', 'code' => '1499'],
            ['nom_local' => 'Assam djérem', 'code' => '1500'],
            ['nom_local' => 'Assam Lomié', 'code' => '1501'],
            ['nom_local' => 'Assam nkubar', 'code' => '1502'],
            ['nom_local' => 'Assam nlong', 'code' => '1503'],
            ['nom_local' => 'Assam stocker', 'code' => '1504'],
            ['nom_local' => 'Assamela / Afrormosia', 'code' => '1104'],
            ['nom_local' => 'Assas', 'code' => '1505'],
            ['nom_local' => 'Assas afum', 'code' => '1506'],
            ['nom_local' => 'Assas nkol', 'code' => '1507'],
            ['nom_local' => 'Assas nkol Buea', 'code' => '1508'],
            ['nom_local' => 'Assas nkol Nyong', 'code' => '1509'],
            ['nom_local' => 'Assas osoé', 'code' => '1984'],
            ['nom_local' => 'Assas songongo', 'code' => '1510'],
            ['nom_local' => 'Asseng Buea', 'code' => '1511'],
            ['nom_local' => 'Assila akoung', 'code' => '1956'],
            ['nom_local' => 'Assila among', 'code' => '1947'],
            ['nom_local' => 'Assila badjoué', 'code' => '2001'],
            ['nom_local' => 'Assila omang', 'code' => '1512'],
            ['nom_local' => 'Asso', 'code' => '1513'],
            ['nom_local' => 'Asystasia', 'code' => '3023'],
            ['nom_local' => 'Ataag', 'code' => '1514'],
            ['nom_local' => 'Atenidia', 'code' => '3216'],
            ['nom_local' => 'Atet badi', 'code' => '1515'],
            ['nom_local' => 'Atet badikik', 'code' => '1516'],
            ['nom_local' => 'Atom', 'code' => '1517'],
            ['nom_local' => 'Atom koé élais', 'code' => '1518'],
            ['nom_local' => 'Atom koé mpom', 'code' => '1924'],
            ['nom_local' => 'Atondo', 'code' => '1519'],
            ['nom_local' => 'Atondo feuilles rouges', 'code' => '1520'],
            ['nom_local' => 'Atondo osoé', 'code' => '1521'],
            ['nom_local' => 'Atong', 'code' => '2012'],
            ['nom_local' => 'Aveuk', 'code' => '1936'],
            ['nom_local' => 'Avodiré', 'code' => '1203'],
            ['nom_local' => 'Avom / Sobu', 'code' => '1523'],
            ['nom_local' => 'Avom PF / Sobu', 'code' => '1522'],
            ['nom_local' => 'Awonog / Akee apple', 'code' => '1526'],
            ['nom_local' => 'Awonog à poils', 'code' => '1524'],
            ['nom_local' => 'Awonog mwapak', 'code' => '1525'],
            ['nom_local' => 'Awoura / Ekop Beli', 'code' => '1527'],
            ['nom_local' => 'Ayinda', 'code' => '1528'],
            ['nom_local' => 'Ayous / Obéché', 'code' => '1105'],
            ['nom_local' => 'Azobé', 'code' => '1106'],
            ['nom_local' => 'Babama', 'code' => '1529'],
            ['nom_local' => 'Badamier', 'code' => '1954'],
            ['nom_local' => 'Bahia', 'code' => '1204'],
            ['nom_local' => 'Bateria', 'code' => '3212'],
            ['nom_local' => 'Bébi', 'code' => '1531'],
            ['nom_local' => 'Bété', 'code' => '1107'],
            ['nom_local' => 'Bibas bibongo', 'code' => '1532'],
            ['nom_local' => 'Bibolo afum', 'code' => '1533'],
            ['nom_local' => 'Bibolo afum Buea', 'code' => '1534'],
            ['nom_local' => 'Bibolo afum man', 'code' => '1535'],
            ['nom_local' => 'Bibolo afum man', 'code' => '1536'],
            ['nom_local' => 'Bibolo afum Nyong', 'code' => '1537'],
            ['nom_local' => 'Bidens', 'code' => '3026'],
            ['nom_local' => 'Bilinga', 'code' => '1308'],
            ['nom_local' => 'Biyobi ngantem', 'code' => '3039'],
            ['nom_local' => 'Biyobi ngantem', 'code' => '3225'],
            ['nom_local' => 'Bodioa', 'code' => '1309'],
            ['nom_local' => 'Bokondo', 'code' => '1538'],
            ['nom_local' => 'Bombax', 'code' => '3093'],
            ['nom_local' => 'Bongo bokoé', 'code' => '1540'],
            ['nom_local' => 'Bongo brousse', 'code' => '1541'],
            ['nom_local' => 'Bongo H (Olon)', 'code' => '1205'],
            ['nom_local' => 'Bongo Jean Marie', 'code' => '1542'],
            ['nom_local' => 'Bongo nkol GF', 'code' => '1543'],
            ['nom_local' => 'Bongo nkol PF', 'code' => '1544'],
            ['nom_local' => 'Bongo nkubar', 'code' => '1545'],
            ['nom_local' => 'Bongo T', 'code' => '1539'],
            ['nom_local' => 'Bongo Yokadouma', 'code' => '1546'],
            ['nom_local' => 'Borreria', 'code' => '3028'],
            ['nom_local' => 'Bossé clair', 'code' => '1108'],
            ['nom_local' => 'Bossé foncé', 'code' => '1109'],
            ['nom_local' => 'Bossipi', 'code' => '1547'],
            ['nom_local' => 'Brazzeia', 'code' => '3141'],
            ['nom_local' => 'Bredelia', 'code' => '3177'],
            ['nom_local' => 'Bridelia', 'code' => '3027'],
            ['nom_local' => 'Bubinga E', 'code' => '1207'],
            ['nom_local' => 'Bubinga rose', 'code' => '1208'],
            ['nom_local' => 'Bubinga rouge', 'code' => '1206'],
            ['nom_local' => 'Canna', 'code' => '3201'],
            ['nom_local' => 'Capsicum', 'code' => '3029'],
            ['nom_local' => 'Capsicum', 'code' => '3030'],
            ['nom_local' => 'Carpolobia (Toubo)', 'code' => '3086'],
            ['nom_local' => 'Casearia', 'code' => '1996'],
            ['nom_local' => 'Casia', 'code' => '3176'],
            ['nom_local' => 'Cassia', 'code' => '1955'],
            ['nom_local' => 'Cassia cam.', 'code' => '3180'],
            ['nom_local' => 'Cassia du siam', 'code' => '1957'],
            ['nom_local' => 'Casspilospernum', 'code' => '3224'],
            ['nom_local' => 'Chêne argenté', 'code' => '1958'],
            ['nom_local' => 'Chrytranthus', 'code' => '3131'],
            ['nom_local' => 'Cissus', 'code' => '3189'],
            ['nom_local' => 'Cissus', 'code' => '3222'],
            ['nom_local' => 'Citrus', 'code' => '1991'],
            ['nom_local' => 'Cleropsis', 'code' => '3213'],
            ['nom_local' => 'Cliptolipsis', 'code' => '3173'],
            ['nom_local' => 'Cognauxia', 'code' => '3198'],
            ['nom_local' => 'Cola', 'code' => '1946'],
            ['nom_local' => 'Combretum', 'code' => '3032'],
            ['nom_local' => 'Commelina', 'code' => '3031'],
            ['nom_local' => 'Costus', 'code' => '3033'],
            ['nom_local' => 'Coula', 'code' => '1549'],
            ['nom_local' => 'Crabwood d’Afrique', 'code' => '1550'],
            ['nom_local' => 'Crabwood de montagne', 'code' => '1551'],
            ['nom_local' => 'Crassosephalum', 'code' => '3195'],
            ['nom_local' => 'Crossopteryx', 'code' => '3095'],
            ['nom_local' => 'Cupressus', 'code' => '1959'],
            ['nom_local' => 'Cussonia', 'code' => '3094'],
            ['nom_local' => 'Cyathula', 'code' => '3034'],
            ['nom_local' => 'Cyathula', 'code' => '3035'],
            ['nom_local' => 'Dabéma', 'code' => '1310'],
            ['nom_local' => 'Dambala', 'code' => '1552'],
            ['nom_local' => 'Dattier de marécage', 'code' => '1553'],
            ['nom_local' => 'Degroce', 'code' => '3037'],
            ['nom_local' => 'Desmodium', 'code' => '3036'],
            ['nom_local' => 'Dessonia', 'code' => '3223'],
            ['nom_local' => 'Diana parallèle', 'code' => '1555'],
            ['nom_local' => 'Diana T', 'code' => '1554'],
            ['nom_local' => 'Diana Z', 'code' => '1311'],
            ['nom_local' => 'Dibétou', 'code' => '1110'],
            ['nom_local' => 'Difou', 'code' => '1312'],
            ['nom_local' => 'Disilipes', 'code' => '3116'],
            ['nom_local' => 'Dissotis', 'code' => '3040'],
            ['nom_local' => 'Dissotis', 'code' => '3041'],
            ['nom_local' => 'Divers', 'code' => '1999'],
            ['nom_local' => 'Divida', 'code' => '1556'],
            ['nom_local' => 'Djimbo', 'code' => '1557'],
            ['nom_local' => 'Dorstenia', 'code' => '3199'],
            ['nom_local' => 'Doussié blanc', 'code' => '1111'],
            ['nom_local' => 'Doussié rouge', 'code' => '1112'],
            ['nom_local' => 'Doussié Sanaga', 'code' => '1113'],
            ['nom_local' => 'Dracina', 'code' => '3227'],
            ['nom_local' => 'Dricorce', 'code' => '3042'],
            ['nom_local' => 'Drynaria', 'code' => '3043'],
            ['nom_local' => 'Drynaria com.', 'code' => '3044'],
            ['nom_local' => 'Drynaria cord.', 'code' => '3045'],
            ['nom_local' => 'Drypetes', 'code' => '1995'],
            ['nom_local' => 'Ebai', 'code' => '1558'],
            ['nom_local' => 'Ebam', 'code' => '1559'],
            ['nom_local' => 'Ebam PF', 'code' => '1560'],
            ['nom_local' => 'Ebap / Adjouaba', 'code' => '1561'],
            ['nom_local' => 'Ebébeng', 'code' => '1562'],
            ['nom_local' => 'Ebegbemva osoé', 'code' => '1563'],
            ['nom_local' => 'Ebène', 'code' => '1114'],
            ['nom_local' => 'Ebiara Edéa', 'code' => '1313'],
            ['nom_local' => 'Ebiara Yaoundé', 'code' => '1564'],
            ['nom_local' => 'Ebin', 'code' => '1565'],
            ['nom_local' => 'Ebin GF', 'code' => '1566'],
            ['nom_local' => 'Ebom', 'code' => '1567'],
            ['nom_local' => 'Ebom osoé GF', 'code' => '1568'],
            ['nom_local' => 'Ebom osoé PF', 'code' => '1569'],
            ['nom_local' => 'Eboukbong', 'code' => '1570'],
            ['nom_local' => 'Eboukbong Dja', 'code' => '1571'],
            ['nom_local' => 'Edip mbazoa', 'code' => '1572'],
            ['nom_local' => 'Edip naga', 'code' => '3159'],
            ['nom_local' => 'Edjujongo / endjojongui', 'code' => '1573'],
            ['nom_local' => 'Edou', 'code' => '1574'],
            ['nom_local' => 'Efobolo', 'code' => '1575'],
            ['nom_local' => 'Efok afum / Poré poré', 'code' => '1576'],
            ['nom_local' => 'Efok ahié', 'code' => '1577'],
            ['nom_local' => 'Efok ayous nkol', 'code' => '1578'],
            ['nom_local' => 'Efok ayous osoé', 'code' => '1579'],
            ['nom_local' => 'Efok bilobi', 'code' => '1580'],
            ['nom_local' => 'Efulkumba', 'code' => '2015'],
            ['nom_local' => 'Eguela', 'code' => '3046'],
            ['nom_local' => 'Ekaba', 'code' => '1314'],
            ['nom_local' => 'Ekammikongo', 'code' => '1581'],
            ['nom_local' => 'Ekang élon', 'code' => '1582'],
            ['nom_local' => 'Ekem', 'code' => '1583'],
            ['nom_local' => 'Ekobem Edéa', 'code' => '1584'],
            ['nom_local' => 'Ekobem essoulé', 'code' => '1585'],
            ['nom_local' => 'Ekobem koumou', 'code' => '1586'],
            ['nom_local' => 'Ekokoa', 'code' => '3047'],
            ['nom_local' => 'Ekom', 'code' => '1940'],
            ['nom_local' => 'Ekong', 'code' => '1587'],
            ['nom_local' => 'Ekop andingding ntuma', 'code' => '1588'],
            ['nom_local' => 'Ekop D', 'code' => '1589'],
            ['nom_local' => 'Ekop ewolet', 'code' => '1590'],
            ['nom_local' => 'Ekop F', 'code' => '1591'],
            ['nom_local' => 'Ekop G', 'code' => '1592'],
            ['nom_local' => 'Ekop GH', 'code' => '1593'],
            ['nom_local' => 'Ekop I', 'code' => '1594'],
            ['nom_local' => 'Ekop J', 'code' => '1595'],
            ['nom_local' => 'Ekop léké', 'code' => '1596'],
            ['nom_local' => 'Ekop mfang', 'code' => '1597'],
            ['nom_local' => 'Ekop naga akolodo', 'code' => '1598'],
            ['nom_local' => 'Ekop naga nord-ouest', 'code' => '1599'],
            ['nom_local' => 'Ekop ngombé GF', 'code' => '1600'],
            ['nom_local' => 'Ekop ngombé mamelle', 'code' => '1601'],
            ['nom_local' => 'Ekop nkan', 'code' => '1602'],
            ['nom_local' => 'Ekop ribi PF', 'code' => '1603'],
            ['nom_local' => 'Ekop tani', 'code' => '1604'],
            ['nom_local' => 'Ekouné', 'code' => '1315'],
            ['nom_local' => 'Ekoussek', 'code' => '1925'],
            ['nom_local' => 'Ekul ngom', 'code' => '3049'],
            ['nom_local' => 'Ele Bomba', 'code' => '1605'],
            ['nom_local' => 'Elé bomba', 'code' => '1949'],
            ['nom_local' => 'Elé kos', 'code' => '1606'],
            ['nom_local' => 'Elé kos osoé', 'code' => '1607'],
            ['nom_local' => 'Elé mendog', 'code' => '1608'],
            ['nom_local' => 'Elé méveng', 'code' => '1609'],
            ['nom_local' => 'Elé ngek', 'code' => '1610'],
            ['nom_local' => 'Elemetok', 'code' => '1612'],
            ['nom_local' => 'Elemetok osoé', 'code' => '1613'],
            ['nom_local' => 'Elephantopus', 'code' => '3050'],
            ['nom_local' => 'Elo', 'code' => '1614'],
            ['nom_local' => 'Emien', 'code' => '1316'],
            ['nom_local' => 'Emien marécage', 'code' => '1615'],
            ['nom_local' => 'Emilia', 'code' => '3051'],
            ['nom_local' => 'Enak', 'code' => '1616'],
            ['nom_local' => 'Enangam', 'code' => '1617'],
            ['nom_local' => 'Encistrocarpus', 'code' => '3178'],
            ['nom_local' => 'Encomas', 'code' => '3111'],
            ['nom_local' => 'Endjojongui évélé', 'code' => '1618'],
            ['nom_local' => 'Endon', 'code' => '1619'],
            ['nom_local' => 'Endon nkol', 'code' => '1620'],
            ['nom_local' => 'Enée', 'code' => '3053'],
            ['nom_local' => 'Enga am', 'code' => '1621'],
            ['nom_local' => 'Engam mauve', 'code' => '1622'],
            ['nom_local' => 'Engam rouge', 'code' => '1623'],
            ['nom_local' => 'Engang osoé', 'code' => '1624'],
            ['nom_local' => 'Engela / Aboé', 'code' => '1625'],
            ['nom_local' => 'Engokom', 'code' => '1626'],
            ['nom_local' => 'Engokom feuilles rouges', 'code' => '1627'],
            ['nom_local' => 'Engokom ntoa', 'code' => '1628'],
            ['nom_local' => 'Engokom osoé', 'code' => '1629'],
            ['nom_local' => 'Entada', 'code' => '3123'],
            ['nom_local' => 'Epaterium', 'code' => '3179'],
            ['nom_local' => 'Erythricocca', 'code' => '3169'],
            ['nom_local' => 'Esabem', 'code' => '1630'],
            ['nom_local' => 'Eseng GF', 'code' => '1631'],
            ['nom_local' => 'Essak / Alow kouaka', 'code' => '1632'],
            ['nom_local' => 'Essane', 'code' => '1633'],
            ['nom_local' => 'Essang afan', 'code' => '1634'],
            ['nom_local' => 'Essesang', 'code' => '1635'],
            ['nom_local' => 'Essok', 'code' => '1636'],
            ['nom_local' => 'Essombi', 'code' => '1637'],
            ['nom_local' => 'Essombi ékouk', 'code' => '1638'],
            ['nom_local' => 'Esson', 'code' => '1639'],
            ['nom_local' => 'Etat mbai', 'code' => '1640'],
            ['nom_local' => 'Etimoé', 'code' => '1317'],
            ['nom_local' => 'Etoan', 'code' => '1641'],
            ['nom_local' => 'Etup / Arbre à pain', 'code' => '1644'],
            ['nom_local' => 'Etup ngom', 'code' => '1642'],
            ['nom_local' => 'Etup osoé', 'code' => '1643'],
            ['nom_local' => 'Eucalyptus', 'code' => '1960'],
            ['nom_local' => 'Eucalyptus', 'code' => '1961'],
            ['nom_local' => 'Eucalyptus', 'code' => '1962'],
            ['nom_local' => 'Eucalyptus', 'code' => '1963'],
            ['nom_local' => 'Eugenia', 'code' => '1987'],
            ['nom_local' => 'Euphorbe', 'code' => '3054'],
            ['nom_local' => 'Evea osoé', 'code' => '1645'],
            ['nom_local' => 'Eveuskulu', 'code' => '1931'],
            ['nom_local' => 'Eveuss', 'code' => '1646'],
            ['nom_local' => 'Eveuss à PF', 'code' => '1647'],
            ['nom_local' => 'Evot', 'code' => '1648'],
            ['nom_local' => 'Evoula nkol', 'code' => '1649'],
            ['nom_local' => 'Evoula PF', 'code' => '1650'],
            ['nom_local' => 'Evoula/Evino', 'code' => '1651'],
            ['nom_local' => 'Evoun', 'code' => '1652'],
            ['nom_local' => 'Evovone / Tulipier', 'code' => '1653'],
            ['nom_local' => 'Evoyé', 'code' => '1654'],
            ['nom_local' => 'Ewolet', 'code' => '1655'],
            ['nom_local' => 'Ewolet adjap', 'code' => '1656'],
            ['nom_local' => 'Ewolet mont Cameroun', 'code' => '1657'],
            ['nom_local' => 'Eyabé', 'code' => '1658'],
            ['nom_local' => 'Eyalzom', 'code' => '3055'],
            ['nom_local' => 'Eyek', 'code' => '1318'],
            ['nom_local' => 'Eyen gwé', 'code' => '1659'],
            ['nom_local' => 'Eyong', 'code' => '1209'],
            ['nom_local' => 'Eyoum', 'code' => '1660'],
            ['nom_local' => 'Eyoum à PF', 'code' => '1661'],
            ['nom_local' => 'Eyoum blanc', 'code' => '1662'],
            ['nom_local' => 'Eyoum foncé', 'code' => '1663'],
            ['nom_local' => 'Eyoum rouge', 'code' => '1664'],
            ['nom_local' => 'Faro', 'code' => '1319'],
            ['nom_local' => 'Faro mezilli', 'code' => '1665'],
            ['nom_local' => 'Fia / Avocatier', 'code' => '1666'],
            ['nom_local' => 'Ficus', 'code' => '3231'],
            ['nom_local' => 'Ficus elastica', 'code' => '3120'],
            ['nom_local' => 'Ficus vogiliana', 'code' => '1985'],
            ['nom_local' => 'Flamboyant', 'code' => '1964'],
            ['nom_local' => 'Fofo afan', 'code' => '3138'],
            ['nom_local' => 'Fraké / Limba', 'code' => '1320'],
            ['nom_local' => 'Framiré', 'code' => '1115'],
            ['nom_local' => 'Fromager / Ceiba', 'code' => '1321'],
            ['nom_local' => 'Gandu', 'code' => '1667'],
            ['nom_local' => 'Gheombi', 'code' => '1668'],
            ['nom_local' => 'Gloriosa', 'code' => '3161'],
            ['nom_local' => 'Glossacalyx', 'code' => '3137'],
            ['nom_local' => 'Gmelina', 'code' => '1965'],
            ['nom_local' => 'Gnetum afri.', 'code' => '3057'],
            ['nom_local' => 'Gnetum boch.', 'code' => '3058'],
            ['nom_local' => 'Gombé', 'code' => '1322'],
            ['nom_local' => 'Gombé zing', 'code' => '1669'],
            ['nom_local' => 'Goyavier', 'code' => '3099'],
            ['nom_local' => 'Hensia', 'code' => '1981'],
            ['nom_local' => 'Hévéa', 'code' => '2018'],
            ['nom_local' => 'Hibiscus', 'code' => '3156'],
            ['nom_local' => 'Homania', 'code' => '3171'],
            ['nom_local' => 'Hymenocardia', 'code' => '3098'],
            ['nom_local' => 'Iantandza / Evouvous', 'code' => '1323'],
            ['nom_local' => 'Ilomba', 'code' => '1324'],
            ['nom_local' => 'Impatience', 'code' => '3194'],
            ['nom_local' => 'Ipomea', 'code' => '3187'],
            ['nom_local' => 'Iroko', 'code' => '1116'],
            ['nom_local' => 'Izombé', 'code' => '1670'],
            ['nom_local' => 'Jacquier', 'code' => '1966'],
            ['nom_local' => 'Jaterosa', 'code' => '3188'],
            ['nom_local' => 'Johimbé', 'code' => '1671'],
            ['nom_local' => 'Kaa', 'code' => '1672'],
            ['nom_local' => 'Kaéla', 'code' => '2016'],
            ['nom_local' => 'Kaka afan', 'code' => '1673'],
            ['nom_local' => 'Kakoa afan', 'code' => '1675'],
            ['nom_local' => 'Kakoa avié', 'code' => '1676'],
            ['nom_local' => 'Kakoa man', 'code' => '1674'],
            ['nom_local' => 'Kakoa Man', 'code' => '1677'],
            ['nom_local' => 'Kal nganda (Batanga)', 'code' => '1678'],
            ['nom_local' => 'Kala', 'code' => '1679'],
            ['nom_local' => 'Kanda / Ovan', 'code' => '1681'],
            ['nom_local' => 'Kanda GF', 'code' => '1680'],
            ['nom_local' => 'Kangon (Bibaya)', 'code' => '1682'],
            ['nom_local' => 'Kapokier', 'code' => '1683'],
            ['nom_local' => 'Kas / Kaso', 'code' => '1684'],
            ['nom_local' => 'Kassémanga', 'code' => '1685'],
            ['nom_local' => 'Kassémanga sanaga/Hog Plum', 'code' => '1686'],
            ['nom_local' => 'Kekelé', 'code' => '1687'],
            ['nom_local' => 'Kiasosé', 'code' => '1688'],
            ['nom_local' => 'Kibakoko à feuilles argentées', 'code' => '1689'],
            ['nom_local' => 'Kibakoko à feuilles roussâtres', 'code' => '1690'],
            ['nom_local' => 'Kodabéma / Nom esseng', 'code' => '1796'],
            ['nom_local' => 'Koffi afan', 'code' => '3167'],
            ['nom_local' => 'Kondroti', 'code' => '1325'],
            ['nom_local' => 'Korna', 'code' => '1930'],
            ['nom_local' => 'Kossipo', 'code' => '1117'],
            ['nom_local' => 'Kotibé', 'code' => '1118'],
            ['nom_local' => 'Koto', 'code' => '1326'],
            ['nom_local' => 'Kpakpa élé', 'code' => '1691'],
            ['nom_local' => 'Kumbi', 'code' => '1327'],
            ['nom_local' => 'Laméa kert', 'code' => '2014'],
            ['nom_local' => 'Landa', 'code' => '1328'],
            ['nom_local' => 'Landolfia', 'code' => '3191'],
            ['nom_local' => 'Lannea', 'code' => '3101'],
            ['nom_local' => 'Lapportea', 'code' => '3062'],
            ['nom_local' => 'Lapportea', 'code' => '3063'],
            ['nom_local' => 'Lati', 'code' => '1329'],
            ['nom_local' => 'Lati parallèle', 'code' => '1330'],
            ['nom_local' => 'Lavigeria (Ekol ngom)', 'code' => '3060'],
            ['nom_local' => 'Ledé osoé', 'code' => '1692'],
            ['nom_local' => 'Leea', 'code' => '3064'],
            ['nom_local' => 'Leea', 'code' => '3065'],
            ['nom_local' => 'Lepidobotrys', 'code' => '1693'],
            ['nom_local' => 'Likeno', 'code' => '3221'],
            ['nom_local' => 'Likoumba (Bibaya)', 'code' => '1694'],
            ['nom_local' => 'Lindjala', 'code' => '1695'],
            ['nom_local' => 'Lindjala banon', 'code' => '1696'],
            ['nom_local' => 'Lindjala Kumba', 'code' => '1697'],
            ['nom_local' => 'Lippia', 'code' => '3066'],
            ['nom_local' => 'Lo', 'code' => '1698'],
            ['nom_local' => 'Longhi', 'code' => '1210'],
            ['nom_local' => 'Lotofa / Nkanang', 'code' => '1212'],
            ['nom_local' => 'Macaranga', 'code' => '3025'],
            ['nom_local' => 'Makoré / Douka', 'code' => '1119'],
            ['nom_local' => 'Mambodé', 'code' => '1332'],
            ['nom_local' => 'Mankwasadum', 'code' => '1699'],
            ['nom_local' => 'Manniophyton', 'code' => '3067'],
            ['nom_local' => 'Mantaly', 'code' => '1967'],
            ['nom_local' => 'Maranthocloa', 'code' => '3209'],
            ['nom_local' => 'Maxia', 'code' => '3121'],
            ['nom_local' => 'Mbakoa bezombo', 'code' => '1700'],
            ['nom_local' => 'Mbambandi', 'code' => '1701'],
            ['nom_local' => 'Mbanegue', 'code' => '1702'],
            ['nom_local' => 'Mbang mbazoa afum', 'code' => '1703'],
            ['nom_local' => 'Mbang mbazoa avié', 'code' => '1704'],
            ['nom_local' => 'Mbanga Campo', 'code' => '1705'],
            ['nom_local' => 'Mbarmbat', 'code' => '1706'],
            ['nom_local' => 'Mbasum elé', 'code' => '1932'],
            ['nom_local' => 'Mbazoa', 'code' => '1707'],
            ['nom_local' => 'Mbazoa littoral', 'code' => '1708'],
            ['nom_local' => 'Mbel man', 'code' => '1709'],
            ['nom_local' => 'Mbel ngom', 'code' => '3102'],
            ['nom_local' => 'Mbélé', 'code' => '1710'],
            ['nom_local' => 'Mbikam', 'code' => '1711'],
            ['nom_local' => 'Mbouboui', 'code' => '3069'],
            ['nom_local' => 'Mebememgono', 'code' => '1433'],
            ['nom_local' => 'Mebememgono', 'code' => '1434'],
            ['nom_local' => 'Mebenga osoé', 'code' => '1712'],
            ['nom_local' => 'Medouxandra', 'code' => '3140'],
            ['nom_local' => 'Megafrinium', 'code' => '3215'],
            ['nom_local' => 'Mékoa', 'code' => '1713'],
            ['nom_local' => 'Memecylon', 'code' => '1986'],
            ['nom_local' => 'Mengamenjanga', 'code' => '1926'],
            ['nom_local' => 'Mengnegues elé', 'code' => '1938'],
            ['nom_local' => 'Meniuminsi', 'code' => '1982'],
            ['nom_local' => 'Meniuminsi ram. ailés', 'code' => '1714'],
            ['nom_local' => 'Meniuminsi ram. anguleux', 'code' => '1715'],
            ['nom_local' => 'Mévini osoé', 'code' => '1716'],
            ['nom_local' => 'Meyomu ébé', 'code' => '1717'],
            ['nom_local' => 'Mfang à poils', 'code' => '1718'],
            ['nom_local' => 'Mfang mvanda', 'code' => '1719'],
            ['nom_local' => 'Mfas', 'code' => '1720'],
            ['nom_local' => 'Mfas asia', 'code' => '1721'],
            ['nom_local' => 'Mfas osoé', 'code' => '1722'],
            ['nom_local' => 'Mféneg', 'code' => '1723'],
            ['nom_local' => 'Miama', 'code' => '1724'],
            ['nom_local' => 'Miasmingomo', 'code' => '1725'],
            ['nom_local' => 'Miasmingomo ntoa', 'code' => '1726'],
            ['nom_local' => 'Minsi', 'code' => '1727'],
            ['nom_local' => 'Moabi', 'code' => '1120'],
            ['nom_local' => 'Moambé jaune', 'code' => '1728'],
            ['nom_local' => 'Moka', 'code' => '1729'],
            ['nom_local' => 'Moka tisongo', 'code' => '1730'],
            ['nom_local' => 'Mondia', 'code' => '3170'],
            ['nom_local' => 'Mongui nogohop', 'code' => '2013'],
            ['nom_local' => 'Movingui', 'code' => '1213'],
            ['nom_local' => 'Mposa', 'code' => '1731'],
            ['nom_local' => 'Mtanda évélé', 'code' => '1732'],
            ['nom_local' => 'Mubala', 'code' => '1733'],
            ['nom_local' => 'Mukulungu', 'code' => '1333'],
            ['nom_local' => 'Mukumari / Cordia d\'Afrique', 'code' => '1548'],
            ['nom_local' => 'Mukuna', 'code' => '3204'],
            ['nom_local' => 'Musizi', 'code' => '1755'],
            ['nom_local' => 'Mutondo', 'code' => '1334'],
            ['nom_local' => 'Mutondo sans glande', 'code' => '1735'],
            ['nom_local' => 'Mvan', 'code' => '1736'],
            ['nom_local' => 'Mvanda', 'code' => '1737'],
            ['nom_local' => 'Mvié élé', 'code' => '1738'],
            ['nom_local' => 'Mvié mvou', 'code' => '1739'],
            ['nom_local' => 'Mvomba', 'code' => '1939'],
            ['nom_local' => 'Naga', 'code' => '1335'],
            ['nom_local' => 'Naga parallèle', 'code' => '1336'],
            ['nom_local' => 'Napoleona', 'code' => '3136'],
            ['nom_local' => 'Ndango', 'code' => '1740'],
            ['nom_local' => 'Ndasono', 'code' => '1741'],
            ['nom_local' => 'Ndik', 'code' => '1742'],
            ['nom_local' => 'Ndimbi', 'code' => '1743'],
            ['nom_local' => 'Nding', 'code' => '1744'],
            ['nom_local' => 'Nditik', 'code' => '1745'],
            ['nom_local' => 'Ndongo makuba', 'code' => '1746'],
            ['nom_local' => 'Neem', 'code' => '1968'],
            ['nom_local' => 'Nenuphar', 'code' => '3236'],
            ['nom_local' => 'Neoboutonia', 'code' => '3235'],
            ['nom_local' => 'Ngando', 'code' => '3234'],
            ['nom_local' => 'Nganga', 'code' => '1337'],
            ['nom_local' => 'Ngobissolbo', 'code' => '1747'],
            ['nom_local' => 'Ngobissolbo PF', 'code' => '1748'],
            ['nom_local' => 'Ngom ntanan', 'code' => '1749'],
            ['nom_local' => 'Nguendemboy', 'code' => '1750'],
            ['nom_local' => 'Nguendemboy osoé', 'code' => '1751'],
            ['nom_local' => 'Ngues', 'code' => '1752'],
            ['nom_local' => 'Nieuk', 'code' => '1753'],
            ['nom_local' => 'Niové', 'code' => '1338'],
            ['nom_local' => 'Nka', 'code' => '1754'],
            ['nom_local' => 'Nkok élé', 'code' => '1756'],
            ['nom_local' => 'Nkubar élé', 'code' => '1757'],
            ['nom_local' => 'Nlighedi', 'code' => '1758'],
            ['nom_local' => 'Nom abam', 'code' => '1760'],
            ['nom_local' => 'Nom abem osoé', 'code' => '1761'],
            ['nom_local' => 'Nom abem osoé PF', 'code' => '1762'],
            ['nom_local' => 'Nom abéna', 'code' => '1763'],
            ['nom_local' => 'Nom abip elé', 'code' => '1933'],
            ['nom_local' => 'Nom adjap osoé', 'code' => '1764'],
            ['nom_local' => 'Nom akadak / Akarak', 'code' => '1765'],
            ['nom_local' => 'Nom akela', 'code' => '1766'],
            ['nom_local' => 'Nom akondok', 'code' => '1934'],
            ['nom_local' => 'Nom akui', 'code' => '1767'],
            ['nom_local' => 'Nom andok', 'code' => '1768'],
            ['nom_local' => 'Nom andok PF', 'code' => '1769'],
            ['nom_local' => 'Nom angoan', 'code' => '1927'],
            ['nom_local' => 'Nom Angossa', 'code' => '1993'],
            ['nom_local' => 'Nom asila abim', 'code' => '1770'],
            ['nom_local' => 'Nom assas', 'code' => '1992'],
            ['nom_local' => 'Nom assas nkol Buea', 'code' => '1771'],
            ['nom_local' => 'Nom assila nkubar', 'code' => '1772'],
            ['nom_local' => 'Nom assila sanaga', 'code' => '1773'],
            ['nom_local' => 'Nom atet', 'code' => '1774'],
            ['nom_local' => 'Nom atet barenka', 'code' => '1775'], 
        ];

        foreach ($essences as $essence) {
            Essence::create($essence);
        }
    }
}
